############################
## CHANGE THESE
############################

baseURL: "https://finn-artmann.github.io/"
title: Finn's Blog >

############################
## MISC
############################

enableEmoji: true
disableKinds: ["taxonomy", "term"]
languageCode: "en-us"
enableRobotsTXT: true

theme: 
 - hugo-embed-pdf-shortcode

enableInlineShortcodes: true
