############################
## CHANGE THESE
############################

baseURL: "https://Finn-Artmann.github.io/finnblog-qubt"
title: finnblog-qubt

############################
## MISC
############################

enableEmoji: true
disableKinds: ["taxonomy", "term"]
languageCode: "en-us"
enableRobotsTXT: true
