############################
## Author
############################

author:
  name: Finn-Artmann
  image: author.png
  greeting: "[![Typing SVG](https://readme-typing-svg.demolab.com?font=Fira+Code&pause=10000&color=8B8B8B&background=FFFFFF00&center=true&random=true&width=800&lines=Hello%2C+World!+You're+at+the+right+place+for+tech+inspiration!;Loading...+Welcome+to+your+next+favorite+tech+blog!;01001000+01100101+01101100+01101100+01101111!;Welcome!+You've+successfully+debugged+your+way+to+this+page.;Welcome!+You've+successfully+debugged+your+way+to+this+page.;May+your+variables+always+be+initialized%2C+and+your+bugs+minimal.;Welcome%2C+friend.;Syntax+check+passed.+Let%E2%80%99s+start!;Do+or+do+not.+There+is+no+try.+;I+solemnly+swear+I+am+up+to+something+geeky.;Welcome%2C+Neo.+Let%E2%80%99s+see+how+deep+this+rabbit+hole+goes.;Open+the+pod+bay+doors%2C+HAL.+It's+time+to+read+this+blog!;The+cake+is+a+lie%2C+but+this+blog+isn%E2%80%99t!;Welcome+to+the+blog%2C+where+no+coder+has+gone+before!;The+blog+has+been+provisioned.+Enjoy+the+uptime!;Docker+run+%E2%80%93it+blog_inspiration%3Alatest.+Welcome+aboard!)](https://git.io/typing-svg)"
  icon: ":wave:"

############################
## Links
############################

links:
  - github: https://github.com/Finn-Artmann/
  # - link: https://github.com/Finn-Artmann/Finns-Blog#readme
  # - website: 
  # - x-twitter: 
  # - mastodon: 
  # - linkedin: 
  # - instagram: 
  # - reddit: 
  # - telegram: 
  # - whatsapp: 
  # - signal: 
  # - codepen: 
  # - dev: 
  # - email: 
  # - discord: 
  # - orcid: 
  # - slack: 
  # - stack-overflow: 
  # - twitch: 
  # - patreon: 
  # - soundcloud: 
  # - dribbble: 
  # - stack-exchange: 
  # - tiktok: 
  # - youtube: 
  # - keybase: 
  # - flickr: 
  # - tumblr: 
  # - kickstarter: 
  # - snapchat:
  # - bluesky: 
  # - bitbucket: 
  # - bandcamp: 
  # - etsy: 
  # - spotify: 
  # - pinterest: 
  # - strava: 
  # - untappd: 
  # - skype: 
  # - medium: 
  # - foursquare: 
  # - apple: 
  # - amazon:
  # - google:
  # - paypal:
  # - windows:

###############################
## OpenGraph & Twitter Cards
###############################

title: Finns-Blog
description: "Site build with Qubt & Hugo"
images:
  - thumbnail.png
